import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';
import GlobalProvider from '@/providers/GlobalProvider';

export const metadata: Metadata = {
	title: 'Real Estate',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased">
				<GlobalProvider>{children}</GlobalProvider>
			</body>
		</html>
	);
}
